// Dados de demonstração (fictícios). Em produção viriam de uma API/planilha da ONG.
// fabricKg = tecido reaproveitado; waterL = água economizada; co2Kg = CO2 evitado.
const PRODUCTS = [
  { id: 1, img: "img/jaqueta.jpg", name: "Jaqueta patchwork jeans", cat: "Roupas", price: 389, artisan: "Maria das Graças", hours: 14, fabricKg: 1.8, waterL: 5400, co2Kg: 9.2, colors: ["#25456B", "#5C82A8", "#E0A526"], story: "Esta jaqueta começou como uma pilha de calças jeans doadas por uma confecção que ia descartá-las. Maria das Graças separou os retalhos por tom e textura e foi encaixando cada pedaço como um quebra-cabeça, com costuras aparentes em linha clara. Nenhuma jaqueta sai igual à outra. Ela levou 14 horas para ficar pronta." },
  { id: 2, name: "Vestido envelope de camisaria", cat: "Roupas", price: 329, artisan: "Joana Pereira", hours: 10, fabricKg: 1.2, waterL: 3600, co2Kg: 6.1, colors: ["#3F7D5A", "#C9D8B6", "#F2F2EC"], story: "Camisas masculinas de brechó, que seriam descartadas por pequenos defeitos, foram desmontadas por Joana Pereira. Ela aproveitou golas, punhos e listras para criar um vestido de caimento leve. Cada peça combina tecidos diferentes e, por isso, é única." },
  { id: 3, name: "Saia midi de retalhos", cat: "Roupas", price: 219, artisan: "Neuza Alves", hours: 7, fabricKg: 0.9, waterL: 2700, co2Kg: 4.6, colors: ["#B5473A", "#E0A526", "#25456B"], story: "Esta saia nasceu de sobras de uma coleção de malha e algodão estampado. Neuza Alves recortou, combinou as cores e costurou os retalhos em faixas, uma a uma. O resultado é uma saia colorida que mostra de onde vieram os tecidos." },
  { id: 4, img: "img/bolsa.jpg", name: "Bolsa tote de lona", cat: "Acessórios", price: 149, artisan: "Rosa Menezes", hours: 5, fabricKg: 0.7, waterL: 2100, co2Kg: 3.5, colors: ["#8A7B5A", "#D9CFB4", "#17212B"], story: "A lona desta bolsa veio de toldos descartados, que Rosa Menezes lavou, cortou e reforçou à mão nas alças e no fundo. É uma bolsa resistente, pensada para durar muitos anos de uso. A costura aparente faz parte do desenho." },
  { id: 5, name: "Necessaire estampada", cat: "Acessórios", price: 69, artisan: "Cida Ramos", hours: 2, fabricKg: 0.2, waterL: 600, co2Kg: 1.0, colors: ["#C2578A", "#F2C9DC", "#3F7D5A"], story: "Cortinas e tecidos de decoração que sobraram viraram esta necessaire. Cida Ramos escolheu as estampas que combinam entre si e forrou a peça por dentro para durar. É pequena, mas poupa tecido que iria para o lixo." },
  { id: 6, img: "img/turbante.jpg", name: "Turbante de algodão", cat: "Acessórios", price: 59, artisan: "Luzia Matos", hours: 1.5, fabricKg: 0.15, waterL: 450, co2Kg: 0.8, colors: ["#E0A526", "#B5473A", "#F2F2EC"], story: "Este turbante é de crochê, feito com fios de algodão que sobraram da produção do instituto. Luzia Matos trabalha ponto a ponto e define as cores de cada faixa. Como os fios variam de lote, cada turbante tem sua própria combinação de cores." },
  { id: 7, img: "img/colete.jpg", name: "Colete matelassê infantil", cat: "Roupas", price: 189, artisan: "Francisca Lima", hours: 9, fabricKg: 1.4, waterL: 4200, co2Kg: 7.3, colors: ["#17212B", "#5C82A8", "#8A7B5A"], story: "Forros e edredons em bom estado ganharam nova vida neste colete. Francisca Lima fez o matelassê em losangos, que deixa o colete leve e quentinho. É uma peça infantil, feita com o mesmo cuidado dos modelos adultos." },
  { id: 8, name: "Porta-notebook jeans", cat: "Acessórios", price: 129, artisan: "Dalva Souza", hours: 4, fabricKg: 0.6, waterL: 1800, co2Kg: 3.1, colors: ["#25456B", "#17212B", "#E0A526"], story: "Calças jeans descartadas foram transformadas em uma capa resistente para notebook. Dalva Souza forrou o interior com feltro reciclado para proteger o aparelho de arranhões. Cada capa tem um tom de jeans diferente, conforme o tecido que sobrou." }
];
